# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee8f50277a7444229ef62590dcaa6edce5e544f7e5c366520253f292796e8c058419edfbb74731cafd4bd714b0a9b55d857de69d18aa070eea72a024119260d5

test:
  secret_key_base: 8ec3ce4ee9812fb4cad77cf4ffeeedb2f15511fe0927f21b5982a7d6df569b153fff7c30b2bba45f449b98985385afd56d08649f8c26d1c020cbb21c8a97859c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
